### ISSUE TITLE
Possibility in providing fragment files

### ISSUE THREAD

**Issue by ChuanXu1** [Single-Cell-Genomics-Group-CNAG-CRG/TonsilAtlas#1]
Dear TonsilAtlas Team,

Thank you for this great resource.

In addition to the seurat object in https://zenodo.org/record/6340174, is it possible for you to provide fragment files in this stage? Thank you!

**Comment by massonix** [comment]
Hey @ChuanXu1!

We have included 7 additional donors in the revision process. The paper has been accepted, so we have reached a second data freeze, and I'll proceed to update the Zenodo repos, this time including the fragments files.

If you need them ASAP, you can find the raw outputs from cellranger here: [https://zenodo.org/record/6678331](https://zenodo.org/record/6678331)

Hope that helps!

Ramon
