### ISSUE TITLE
fragments files of scATAC-seq

### ISSUE THREAD

**Issue by frucelee** [Single-Cell-Genomics-Group-CNAG-CRG/TonsilAtlas#2]
Hi,

Thanks so much for the atlas. The fragment files of 9 scATAC-seq samples were all the same size (525,744 kb), with only a few cells overlapped when compared to the Seurat object of scATAC-seq. I guess all the fragments files came from the same individuals (particularly, gem_id: m7maqeew_gt2mrtf3; donor id: BCLL-14-T). Is it possible for you to check these files and update them? Thanks in advance.

Really appreciated.

Best,

Lee

**Comment by massonix** [comment]
Hi Lee,

You're absolutely right, sorry I'm just seeing this right now, hopefully this should be updated in the newest [version 3.0](https://zenodo.org/records/11355186)

Ramon
