### ISSUE TITLE
Question about scATAC data analysis reproduction

### ISSUE THREAD

**Issue by JanRose1** [Single-Cell-Genomics-Group-CNAG-CRG/TonsilAtlas#4]
As title says I'm currently going through the reconstruction of the scATAC data analysis and there are results being asked for in QC that haven't been generated in prior steps. For example in filtering we route a path to scATAC-seq/results/Aggregated/. Based on what future cells state. Aggregated is meant to be the direction of the Filtered_BC_Matrices but based on how this code chunk works:

path_to_data <- here::here("/Users/janro123454/Desktop/Russel_Lab_Chromatin/scATACBC/Filtered_peaks_bc_matrixes/aks0q3tw_lsr4h73j/")
tonsil_aggregated <- read_atac_data(path_to_data)
tonsil_aggregated@meta.data$lib_number <- as.data.frame(str_split(row.names(tonsil_aggregated@meta.data), "-", simplify = TRUE))$V2

tonsil_aggregated@meta.data$gem_id <- revalue(
  tonsil_aggregated@meta.data$lib_number,
  c(
    "1" = "jbp85ve3_3179tpob",
    "2" = "sy59df1i_56bwpc10",
    "3" = "aks0q3tw_lsr4h73j",
    "4" = "fnpetv1y_agr9h7v4",
    "5" = "jmjpvq6z_fr6c4nyp",
    "6" = "yja17lfh_kdslhq0g",
    "7" = "u51p7uvm_s5fhku31",
    "8" = "vcan8qd9_sr5u40yg",
    "9" = "dhqzxpdk_h8em75r9",
    "10" = "lacrul5e_67e3wsyf",
    "11" = "lzj8c3xo_ytz0xw8m",
    "12" = "m7maqeew_gt2mrtf3",
    "13" = "xazsjcvt_kzi9e2rf"
  )
)

I'm having trouble understanding if it's supposed to run read_atac_data_path on a single set of data or on all of them simultaneously. Any help would be appeciated.

**Comment by massonix** [comment]
Answered in #5
