### ISSUE TITLE
Data provided for scATACSeq Matrices on Zenodo (Level 2) is all of the same gem ID

### ISSUE THREAD

**Issue by JanRose1** [Single-Cell-Genomics-Group-CNAG-CRG/TonsilAtlas#5]
Greetings again.
It has come to my attention that you may have accidentally provided the same data in every gemID of the scATAC-seq zip. I was comparing the html report of the provided process with what the graphs I was generating in R. Suffice to say the cell counts didn't match. Upon examining the zenodo files I downloaded more closely I realized all of them are of the same size and contain the same summary for "m7maqeew_gt2mrtf3". If possible, can these files be verified to be correct?

**Comment by massonix** [comment]
Thank you so much for brining this to our attention. We have now updated the scATAC-seq.zip file in a [new version 3.0](https://zenodo.org/records/11355186), which should correct the issue that you report.

Many thanks,

Ramon
